// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class PolregiotestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void polregiotest() {
    driver.get("https://polregio.pl/pl/");
    driver.manage().window().setSize(new Dimension(1464, 1032));
    driver.findElement(By.name("start_station")).click();
    driver.findElement(By.name("start_station")).sendKeys("Gdańsk Główny");
    driver.findElement(By.cssSelector(".formcontainer")).click();
    driver.findElement(By.name("end_station")).click();
    driver.findElement(By.name("end_station")).sendKeys("Daleko");
    driver.findElement(By.cssSelector(".formcontainer")).click();
    driver.findElement(By.cssSelector(".submit")).click();
    driver.findElement(By.cssSelector(".submit")).click();
    driver.findElement(By.cssSelector(".submit")).click();
    driver.findElement(By.name("end_station")).click();
    driver.findElement(By.name("end_station")).click();
    driver.findElement(By.name("end_station")).sendKeys("Tczew");
    driver.findElement(By.cssSelector(".formcontainer")).click();
    driver.findElement(By.cssSelector(".submit")).click();
    assertThat(driver.findElement(By.linkText("Gdańsk Główny")).getText(), is("Gdańsk Główny"));
    assertThat(driver.findElement(By.cssSelector("#ember1535 .hide-for-small-only > .price-parts")).getText(), is("13,00 zł"));
    driver.findElement(By.cssSelector(".add-station")).click();
    driver.findElement(By.id("via_input_0")).click();
    driver.findElement(By.id("via_input_0")).sendKeys("Olsztyn Główny");
    driver.findElement(By.id("via_stations_container")).click();
    driver.findElement(By.id("small_search")).click();
    js.executeScript("window.scrollTo(0,7)");
    assertThat(driver.findElement(By.cssSelector(".warning")).getText(), is("Niestety nie udało się odnaleźć połączenia."));
    assertThat(driver.findElement(By.cssSelector(".warning")).getText(), is("Niestety nie udało się odnaleźć połączenia."));
    driver.findElement(By.linkText("Kup bilet na weekend")).click();
    assertThat(driver.findElement(By.cssSelector(".tickets__ticket:nth-child(1) span")).getText(), is("47,00 zł"));
    driver.findElement(By.cssSelector(".network__heading:nth-child(1)")).click();
    assertThat(driver.findElement(By.cssSelector(".network__heading:nth-child(1)")).getText(), is("1. Wybierz ofertę"));
    driver.findElement(By.cssSelector(".navbar__top")).click();
    driver.findElement(By.cssSelector(".navbar__language-button:nth-child(3) > .footer__flag")).click();
    assertThat(driver.findElement(By.cssSelector(".network__heading:nth-child(1)")).getText(), is("1. Select offer"));
    driver.findElement(By.linkText("My account")).click();
    assertThat(driver.findElement(By.cssSelector("h2")).getText(), is("Dlaczego warto założyć konto?"));
  }
}
